
const TRACK_TYPES = {
  REGULAR: "REGULAR",
  VIP: "VIP",
}

const VEHICLE_TYPES = {
  BIKE: "BIKE",
  CAR: "CAR",
  SUV: "SUV",
}

const REG_TRACK_LIMIT = {
  [VEHICLE_TYPES.BIKE]: 4,
  [VEHICLE_TYPES.CAR]: 2,
  [VEHICLE_TYPES.SUV]: 2,
}

const VIP_TRACK_LIMIT = {
  [VEHICLE_TYPES.BIKE]: 0,
  [VEHICLE_TYPES.CAR]: 1,
  [VEHICLE_TYPES.SUV]: 1,
}

const REG_TRACK_PRICE_PER_HR = {
  [VEHICLE_TYPES.BIKE]: 60,
  [VEHICLE_TYPES.CAR]: 120,
  [VEHICLE_TYPES.SUV]: 200,
}

const VIP_TRACK_PRICE_PER_HR = {
  [VEHICLE_TYPES.BIKE]: 0,
  [VEHICLE_TYPES.CAR]: 250,
  [VEHICLE_TYPES.SUV]: 300,
}

module.exports = {
  TRACK_TYPES,
  VEHICLE_TYPES,
  REG_TRACK_LIMIT,
  VIP_TRACK_LIMIT,
  REG_TRACK_PRICE_PER_HR,
  VIP_TRACK_PRICE_PER_HR,
}